sudo: required
services:
  - docker

before_install:
  - docker build -t sauravbiswas16294/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sauravbiswas16294/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react" # app name
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-850335431219"
  bucket_path: "docker-react"
  on: # Monitors master branch to check change in code and deploy it
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

