sudo: required
services:
  - docker

before_install:
  - docker build -t sauravbiswas16294/docker-react -f Dockerfile.dev .

script:
  - docker run sauravbiswas16294/docker-react npm run test -- --coverage